### ISSUE TITLE
Could not open input file: vendor/bin/coveralls

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/travis#37]
`Could not open input file: vendor/bin/coveralls`
happens in 90% of all cases, e.g.[here](https://travis-ci.org/dereuromark/tools/jobs/21131706#L123).

See https://github.com/GotCms/GotCms/commit/999224c72c8278113d4734e9b938a1b61b1d46b7
for a possible fix.

**Comment by dereuromark** [comment]
Could be closed with https://github.com/FriendsOfCake/travis/issues/71

**Comment by josegonzalez** [comment]
Yes.
