### ISSUE TITLE
PSR2 Support

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/travis#47]
So now that CakePHP has swapped over to using PSR2 is it worth updating the Travis project here to start enforcing plugins using the repo to update to be consistent with the framework?

**Comment by ceeram** [comment]
Doesnt it already do this on the cake3 branch? Its using psr2 based rules
there

2015-01-19 11:36 GMT+01:00 David Yell <notifications@github.com>:

**Comment by davidyell** [comment]
Urgh, sorry. Totally missed the 3.x branch!
