### ISSUE TITLE
travis and 2.x branch not working anymore

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/travis#74]
In current travis CI checks it aborts early with

    Found no valid ref to match with version 2.x

etc
Any idea how we can fix things here for those that still need to provide fixes for 2.x branches of plugins etc?

**Comment by berarma** [comment]
I'm trying to use it but I've found two problems:

 - The ref calculation is wrong. The change at 8a6a970d2409b216991e3a8c81c7f021a950e8d6 changes the branch checked but doesn't change the branch returned. Thus, I want to use version 2.10 but master ref is returned.
 - It uses PHPUnit 3.x while I need 4.x or 5.x.

Is anyone working on these?

**Comment by chitoku-k** [comment]
I'm not one who works on this issue but I want to share some tips when I managed to solve them in my project.

- Specifically set `CAKE_REF` to `2.x` where you can avoid its wrong calculation.
- After calling `before_script.sh`, you may `remove` phpunit and then `require` the desired version. Note that CakePHP 2.10 reverted back its supported PHPUnit to ^3.7 for some reason (whereas <6.0.0 works for me). Don't forget to load autoloader afterwards as well.

For further detail, please refer to my working config:
https://github.com/lampager/lampager-cakephp2/blob/003ccb75f3a402b07757cd175786c63580ce4dc1/.travis.yml

**Comment by dereuromark** [comment]
Are you able to make a PR for this repo? Maybe also to README/docs etc?

**Comment by bancer** [comment]
@dereuromark I think this issue can be closed as the fix was applied in https://github.com/FriendsOfCake/travis/pull/75

**Comment by chitoku-k** [comment]
Sorry I've totally forgotten this issue! I personally don't think this issue has been solved because the root cause is that the calls to GitHub API would be likely to fail in the CI environments due to its restriction by rate limits.

**Comment by dereuromark** [comment]
But if no one is interested in fixing this, we can close as works for me - after those many years now.

**Comment by bancer** [comment]
@chitoku-k https://github.com/dereuromark/cakephp-shim project uses this one without failures. Or do I miss something?

**Comment by dereuromark** [comment]
True
https://github.com/dereuromark/cakephp-shim/blob/cake2/.travis.yml seems to work.
Closing then.
